### ISSUE TITLE
Searching on Immich give no match

### ISSUE THREAD

**Issue by frigi83** [v411e/ppim-migrator#3]
Hi thanks for sharing your work. I have tried Immich and a crucial step is the migration from Photoprism, because I have a lot of photos (~ 190'000).

The connection between the two systems works, but it seems that the search is giving nothing (I'm not a programmer), for favorites and albums. Can it be that with the change in release [V1.91.0](https://github.com/immich-app/immich/releases/tag/v1.91.0), the search results (or search key) are also changed and now they don't work.

Can you make a try to confirm that?

**Comment by v411e** [comment]
Hi, thanks for opening the issue, I will have a look in the next few days and see whether it still works for me

**Comment by frigi83** [comment]
Thanks @v411e for your help. I have found on the discussion on Immich this [conversation](https://github.com/immich-app/immich/discussions/6276).

**Comment by v411e** [comment]
Jep, can confirm this issue. Immich search was changed a lot in the last releases, it seems that searching for filenames or paths is not longer possible.

Glad, you found the conversation, I added a [comment](https://github.com/immich-app/immich/discussions/6276#discussioncomment-8064495) there :)

**Comment by v411e** [comment]
> It was possible with Typesense. Now that we removed Typesense that mechanism is temporarily gone with it. We will add it back in the search enhancement work

_Originally posted by alextran1502 in https://github.com/immich-app/immich/discussions/6276#discussioncomment-8067844_

**Comment by frigi83** [comment]
With the new release V1.93.x you can now search by file name o path. But you need the tag "m:" before the path or file name.

**Comment by v411e** [comment]
Oh, thats great news! I just tested it with ppim-migrator and it works again now for v1.93.x
